### ISSUE TITLE
Unable to Gradle Sync using bintray

### ISSUE THREAD

**Issue by vijayakumarmariyappan** [Romancha/android-material-play-pause-view-button#1]
Hi @Romancha ,

Thank you for this library. I was using this library, it worked fine. But recently I got this issue. 
Because of this I unable to build the project. 
It seems you uploaded the binary to bintray which is not working now I guess. 
Is there any workaround to make it work?

Kindly please help me. Thanks in advance :)

**Error while run the project:**
Could not GET 'https://dl.bintray.com/romancha/romancha-repo/com/yanzhenjie/permission/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

**Comment by Romancha** [comment]
@vijayakumarmariyappan Hi!
I will release a fix in a few days

**Comment by vijayakumarmariyappan** [comment]
@Romancha Thanks dude :)

**Comment by Romancha** [comment]
@vijayakumarmariyappan check new readme. Note that the package of PlayPauseView has changed

**Comment by vijayakumarmariyappan** [comment]
@Romancha Thank you so much :)
